# Generated by Django 5.1.4 on 2024-12-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0005_alter_artista_options'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='artistas',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='artistas.artista'),
        ),
    ]
