# Generated by Django 5.1.4 on 2024-12-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_1', models.CharField(max_length=255)),
                ('apellido_2', models.CharField(max_length=255)),
                ('nombre_artistico', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('experiencia', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='artista/documentos/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='artistas.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_url', models.URLField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='artistas.artista')),
            ],
        ),
    ]
