# Generated by Django 5.1.4 on 2024-12-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artista',
            table='artistas_artista',
        ),
    ]
