# Generated by Django 5.1.4 on 2024-12-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0002_alter_artista_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='nombre_artistico',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='artista',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
