# Generated by Django 5.1.4 on 2024-12-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0003_alter_artista_nombre_artistico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='tarifa_hora',
        ),
    ]
