# Generated by Django 5.1.4 on 2025-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0005_alter_artista_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto_url',
            field=models.ImageField(upload_to='fotos/'),
        ),
    ]
